# Generated by Django 3.2.25 on 2024-09-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingenquiry",
            options={
                "ordering": ["-date_submitted"],
                "verbose_name_plural": "Booking Enquiries",
            },
        ),
    ]
