# Generated by Django 3.2.25 on 2024-08-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0002_rename_intructor_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="instructor",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
