# Generated by Django 3.2.25 on 2024-08-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_instructor_primary_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='primary_course',
        ),
    ]
