# Generated by Django 3.2.25 on 2024-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_remove_instructor_primary_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_name',
            field=models.CharField(max_length=5),
        ),
    ]
